name: build_integration
description: >
  Libraries for integrating Dart tools with build systems like bazel
  and build_runner.
# This package is not intended to be published - yet
publish_to: none

dependencies:
  front_end: ^0.1.0
